#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8
Version  : 3.7.6
Release  : 55
URL      : https://files.pythonhosted.org/packages/ae/b0/b79a880f6df38274e47d250edbe4e1dadcf091cb6bef1bc812c3721fe1a2/flake8-3.7.6.tar.gz
Source0  : https://files.pythonhosted.org/packages/ae/b0/b79a880f6df38274e47d250edbe4e1dadcf091cb6bef1bc812c3721fe1a2/flake8-3.7.6.tar.gz
Summary  : the modular source code checker: pep8, pyflakes and co
Group    : Development/Tools
License  : MIT
Requires: flake8-bin = %{version}-%{release}
Requires: flake8-license = %{version}-%{release}
Requires: flake8-python = %{version}-%{release}
Requires: flake8-python3 = %{version}-%{release}
Requires: configparser
Requires: entrypoints
Requires: functools32
Requires: mccabe
Requires: pycodestyle
Requires: pyflakes
Requires: typing
BuildRequires : buildreq-distutils3
BuildRequires : mccabe-python
BuildRequires : nose-python
BuildRequires : pep8-python
BuildRequires : pyflakes-python

%description
Flake8
        ========

%package bin
Summary: bin components for the flake8 package.
Group: Binaries
Requires: flake8-license = %{version}-%{release}

%description bin
bin components for the flake8 package.


%package license
Summary: license components for the flake8 package.
Group: Default

%description license
license components for the flake8 package.


%package python
Summary: python components for the flake8 package.
Group: Default
Requires: flake8-python3 = %{version}-%{release}

%description python
python components for the flake8 package.


%package python3
Summary: python3 components for the flake8 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the flake8 package.


%prep
%setup -q -n flake8-3.7.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550701264
export LDFLAGS="${LDFLAGS} -fno-lto"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flake8
cp LICENSE %{buildroot}/usr/share/package-licenses/flake8/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/flake8

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flake8/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
